### ISSUE TITLE
Not loading after HA upgrade to 2024.1.0

### ISSUE THREAD

**Issue by zoltan65** [mbuchber/ha_heliotherm#21]
HaHeliotherm not starting after upgrade of HA to 2024.1.0. Log bellow:

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 23:18:49 (1 occurrences)
Last logged: 23:18:49

Setup failed for custom integration 'ha_heliotherm': Unable to import component: Exception importing custom_components.ha_heliotherm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ha_heliotherm/__init__.py", line 30, in <module>
    from .const import DEFAULT_NAME, DEFAULT_SCAN_INTERVAL, DOMAIN
  File "/config/custom_components/ha_heliotherm/const.py", line 121, in <module>
    native_unit_of_measurement=TEMP_CELSIUS,
                               ^^^^^^^^^^^^
NameError: name 'TEMP_CELSIUS' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ha_heliotherm

**Comment by JanB1974** [comment]
following

**Comment by PKOE05** [comment]
same error, after upgrade HA 2024.1

**Comment by indymav** [comment]
same here, had to restore core-backup to make it work again

**Comment by JanB1974** [comment]
Updated to 2024.1.2 and it works again!

**Comment by indymav** [comment]
Confirmed! Thank you!!
